version: '2'
services:
  openapi-server1:
    container_name: openapi-server1
    build:
      context: ./eureka
      dockerfile: docker/Dockerfile
    depends_on:
      - mongodb-server
    links:
      - mongodb-server:${MONGODB_HOST}
    ports:
      - "8081:8080"
    environment:
      EUREKA_SERVER_HOST: ${EUREKA_SERVER_HOST}
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_PORT: ${MONGODB_PORT}
      JAVA_OPTS: -Xmx1024m -Xms256m
  openapi-server2:
    container_name: openapi-server2
    build:
      context: ./eureka
      dockerfile: docker/Dockerfile
    depends_on:
      - mongodb-server
    links:
      - mongodb-server:${MONGODB_HOST}
    ports:
      - "8082:8080"
    environment:
      EUREKA_SERVER_HOST: ${EUREKA_SERVER_HOST}
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_PORT: ${MONGODB_PORT}
      JAVA_OPTS: -Xmx1024m -Xms256m
  mongodb-server:
    container_name: mongodb-server
    image: mongo
